version: '2' 

services:
  haproxy:  # Haproxy service  
    image: haproxy  # Official HAProxy image  
    ports:  
      - 80:80  
      - 6379:6379
      - 6380:6380
    container_name: 'haproxy' # Name of the container  
    volumes:  # HAProxy configuration volume mount   
      - './haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'